- name: yum 卸载 ntp
  shell: 'yum remove -y ntp'
  when: 'ansible_distribution in ["CentOS","RedHat"]'
  args:
      warn: false
  ignore_errors: true

- name: 安装 chrony
  package: name=chrony state=present
  when: 'INSTALL_SOURCE != "offline"'

# 离线安装 chrony
- import_tasks: offline.yml
  when: 'INSTALL_SOURCE == "offline"'

- block:
  - name: 配置 chrony server 
    template: src=server-centos.conf.j2 dest=/etc/chrony.conf
    when: 'ansible_distribution in ["CentOS","RedHat"]' 

  - name: 启动 chrony server
    service: name=chronyd state=restarted enabled=yes
    when: 'ansible_distribution in ["CentOS","RedHat"]' 

- block:
  - name: 配置 chrony client
    template: src=client-centos.conf.j2 dest=/etc/chrony.conf
    when: 'ansible_distribution in ["CentOS","RedHat"]' 

  - name: 启动 chrony client 
    service: name=chronyd state=restarted enabled=yes
    when: 'ansible_distribution in ["CentOS","RedHat"]' 

  when: 'inventory_hostname != groups.chrony[0]'